---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mysql-agent
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: {{ .Release.Namespace }}