apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}
  labels:
    app: {{ include "thanos.name" . }}
    chart: {{ include "thanos.chart" . }}
    release: {{ .thanos.Name }}
    heritage: {{ .thanos.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cluster
    port: {{ .Values.global.cluster.port }}
    targetPort: cluster
  selector:
    thanos-peer: "true"