apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}
  labels:
    app: {{ include "thanos.name" . }}
    chart: {{ include "thanos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.global.objstore.configFile }}:
    type: GCS
    config:
      bucket: {{ .Values.gcs.bucket }}
