apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Graphite
        orgId: 1

    datasources:
    - name: prometheus
      type: prometheus
      url: http://{{ .Release.Name }}-prometheus-server:80
      access: proxy
      isDefault: true
#    restartPolicy: OnFailure
#    image: appropriate/curl:latest

