---

backend:
  type: forward
  forward:
    host: logging-fluentd
    port: 24240
    tls:
      enabled: true
      verify: Off

input:
  name: tail
  path: /var/log/containers/*.log
  parser: docker
  tag: kuberenetes
  refreshInterval: 5
  memBufLimit: 5MB
  skipLongLines: On
  positionStore: /fluent-bit/storage/logs.db

filter:
  kubeURL: https://kubernetes.default.svc:443
  kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  mergeJSONLog: On

metrics:
  enabled: true
  listen: 0.0.0.0
  port: 2020

fluent-bit:
  image:
    fluent_bit:
      repository: banzaicloud/fluent-bit
      tag: latest
    pullPolicy: Always

  existingConfigMap: "fluent-bit-config"

  podAnnotation:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/v1/metrics/prometheus"
    prometheus.io/port: "2020"

  extraVolumes: 
    - name: position-store
      emptyDir: {}
    - name: fluentbit-tls
      secret:
        secretName: fluentbit-tls
  extraVolumeMounts:
    - name: position-store
      mountPath: /fluent-bit/storage
    - name: fluentbit-tls
      mountPath: /fluent-bit/ssl
      readOnly: true
  env:
    - name: TLS_PRIVATE_KEY_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: fluentbit-tls
          key: server.key.passphrase
    - name: SHARED_KEY
      valueFrom:
        secretKeyRef:
          name: fluentbit-tls
          key: fluent.shared.key

fluentd:
  plugins:
    elasticsearch:
      enabled: false
      env:
        ES_OUTPUT_HOST: elasticsearch
        ES_OUTPUT_PORT: 9200

  service:
    type: ClusterIP
    externalPort: 80
    ports:
      - name: "monitor-agent"
        protocol: TCP
        containerPort: 24220
      - name: "fluent-input"
        protocol: TCP
        containerPort: 24240
      - name: "prometheus-input"
        protocol: TCP
        containerPort: 24231

  image:
    repository: banzaicloud/fluentd
    tag: v1.1.2

  rbac:
    create: true
    serviceAccountName: default

  configMapOverrideName: "fluentd-config"

  extraVolumes:
    - name: fluentd-tls
      secret:
        secretName: fluentd-tls

  extraVolumeMounts:
    - name: fluentd-tls
      mountPath: /fluentd/etc/ssl/
      readOnly: true

  env:
    - name: TLS_PRIVATE_KEY_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: fluentd-tls
          key: server.key.passphrase

    - name: SHARED_KEY
      valueFrom:
        secretKeyRef:
          name: fluentd-tls
          key: fluent.shared.key
