---

backend:
  type: forward
  forward:
    host: fluentd
    port: 24284
    tls:
      enabled: true
      verify: Off

input:
  name: tail
  path: /var/log/containers/*.log
  parser: docker
  tag: kube.*
  refreshInterval: 5
  memBufLimit: 5MB
  skipLongLines: On
  positionStore: /fluent-bit/storage/logs.db

filter:
  kubeURL: https://kubernetes.default.svc:443
  kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

metrics:
  enabled: true
  listen: 0.0.0.0
  port: 2020

fluent-bit:
  image:
    repository: banzaicloud/fluent-bit
    tag: latest

  existingConfigMap: "fluent-bit-config"

  podAnnotation:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/v1/metrics/prometheus"
    prometheus.io/port: "2020"

  extraVolumes: 
    - name: position-store
      emptyDir: {}
    - name: fluentbit-tls
      secret:
        secretName: fluentbit-tls
  extraVolumeMounts:
    - name: position-store
      mountPath: /fluent-bit/storage
    - name: fluentbit-tls
      mountPath: /fluent-bit/ssl
      readOnly: true
  env:
    - name: TLS_PRIVATE_KEY_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: fluentbit-tls
          key: server.key.passphrase
    - name: SHARED_KEY
      valueFrom:
        secretKeyRef:
          name: fluentbit-tls
          key: fluent.shared.key

fluentd:
  plugins: {}

  image:
    repository: banzaicloud/fluentd
    tag: v1.1.3

  rbac:
    create: true
    serviceAccountName: default

  configMapOverrideName: "fluentd-config"

  extraVolumes:
    - name: fluentd-tls
      secret:
        secretName: fluentd-tls

  extraVolumeMounts:
    - name: fluentd-tls
      mountPath: /fluentd/etc/ssl/
      readOnly: true

  env:
    - name: TLS_PRIVATE_KEY_PASSPHRASE
      valueFrom:
        secretKeyRef:
          name: fluentd-tls
          key: server.key.passphrase

    - name: SHARED_KEY
      valueFrom:
        secretKeyRef:
          name: fluentd-tls
          key: fluent.shared.key
