---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sql-exporter.fullname" . }}
  labels:
    app: {{ include "sql-exporter.name" . }}
    chart: {{ include "sql-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.configFile }}: |
    jobs:
    - name: "clusters_status"
      interval: '1m'
      connections:
      - 'mysql://{{ .Values.database.user }}:{{ .Values.database.password }}@tcp({{ .Values.database.host }}:{{ .Values.database.port }})/{{ .Values.database.db }}?tls=skip-verify'
      queries:
      - name: "clusters_status_count"
        help: "Number of clusters labelled by status"
        labels:
          - "status"
        values:
          - "count"
        query:  |
                SELECT
                  status::text,
                  COUNT(*)::float as count
                FROM clusters
                GROUP BY status;